use only 1 core for windwos test on travis
Multiprocessing is not yet working on windows, due to this
error:

 RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.
        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:
            if __name__ == '__main__':
                freeze_support()
                ...
        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable

Maybe some imports must be moved into functions?

Also windows gives a slightly different result for the same input data.
This comparison of results fails:
======================================================================
FAIL: test_results_of_tutorial (test_core.TestCase)
Test against publication of Sens-Schoenfelder and Wegler (2006)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "...\lib\site-packages\qopen\tests\test_core.py", line 183, in test_results_of_tutorial
    self.assertEqual(result, result2)
AssertionError: Order[77 chars]6, 2.572353589769293e-06, 1.7469527514239988e-[8653 chars]]))]) !=
                Order[77 chars]6, 2.6656617951445806e-06,1.7469527514239988e[8645 chars]]))])

This is a bit strange, but the difference is not much.